spring.application.name=autocare-pro-vmms

#CONFIGURACIONES PARA MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/autocare_pro_vmms
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver